### ISSUE TITLE
fail to configure but no errors displayed

### ISSUE THREAD

**Issue by samuele2723** [madmachinations/home-assistant-todoist-shopping-list#1]
Hello, i am quite experienced HA user, i followed your instructions but every time i add the integration it report success but then shows error in the display.

there is no error in the log
![Schermata 2023-05-02 alle 23 35 51](https://user-images.githubusercontent.com/66970905/235791365-173cb04d-625f-425f-8480-bd4372f0b693.png)
![Schermata 2023-05-02 alle 22 58 08](https://user-images.githubusercontent.com/66970905/235791370-aad718ed-ed81-4386-bc92-9b764f75a25e.png)

i tried to reset the API id several time and check everything on todolist side. no luck

**Comment by samuele2723** [comment]
Hello, thanks for quick reply.

i didn’t have activated initially, but i did later. After that i restarted HA and also reconfigured the integration but no luck so far.

any advice for further troubleshoot?

**Comment by madmachinations** [comment]
Hmmm, after activating it, did you just "reload" this integration, or did you delete it entirely and redo the setup process?

I'd recommend deleting it and redoing the setup process, if you didn't do that. Just to eliminate anything weird that could be happening.

My next thought is wondering how you are running HA? Is it HA OS? Is it a stand alone install? Is it a custom container-based solution?

Because if it's HA OS, I wonder if maybe it is behaving a bit differently or something. I have never spent much time with HA OS, I tried it once and it annoyed me. But I seem to recall it having a whole "add-ons" store thing for setting up custom components and the like? So I wonder if there is some interference there I'm not aware of.

The fact that there are no errors in the logs makes me wonder if it is HA OS, and if it is running the integration in some kind of sandboxed/self-contained environment. Or perhaps on HA OS it has disabled exception logs from showing because it's supposed to be a more "end-user" experience?

When a custom component is installed, HA is supposed to look at the manifest and resolve any dependencies it needs. In this case, it only needs `aiohttp` - which should be installed already in your environment. But I haven't listed it within the manifest, so if it is running it in some kind of sandbox - you could try adding aiohttp to the dependencies list in there, delete the integration and restart HA so it's loading from scratch?

The next thought is your Todoist API key itself. Todoist have two kinds of API key. They have ones for developers, where you are making an API key to make an app that integrates with Todoist. And the other kind is the personal API key, which every account already has, and you just need to go and get it from your personal account settings. This integration needs the *personal* API key, *not* the developer kind.

Other than those thoughts, I'm at a loss tbh, it should just work if you have the shopping list integration enabled, and you have correctly configured your Todoist account.

The only other info I can provide you is a breakdown of the steps this integration does, and where it could fail:

1) It will try to use the Todoist API key you provided in setup to connect with the Todoist API. This key should be a key on your personal account, not a developer account, you can find it in your integration account settings when you go on the Todoist app. If it fails at this point, there will be no error. HA will just show that the integration is broken for some reason.

2) If it connects successfully to Todoist, it will try and locate a project on your Todoist account called "Alexa Shopping List". This project is created automatically when you link your Todoist and your Alexa accounts. If it does not find this project, an error will occur and should appear in the logs as an Exception saying something like "Unable to find Alexa Shopping List".

3) It will get all active tasks under the "Alexa Shopping List" project, it will compare them to the items on your HA shopping list currently. If they do not match, it will replace all the active items on your HA shopping list with this data. It will repeat this process every minute.

4) When you add, edit, delete, or check an item on your HA shopping list - this integration will mirror that action on your Todoist "Alexa Shopping List". Todoist then in-turn will mirror that on your Alexa account's shopping list.

I hope that this information helps you debug it and find where the problem is. If there's anything else I can answer to help then please let me know, and if you find out more please do post back in this issue. If you can get me an error message from the logs, that would go a long way towards finding the answer.

**Comment by samuele2723** [comment]
Hello, thanks for the very extended tips, some quick reply here then i will dig through your full suggestion tonight:

- i use HA core in docker, so kind of clean setup and no supervisor environment
- The API i get give me “success” is the one from this page attached (sorry italian but you can tell)
![FAAFBAAB-8AD8-4C37-BA75-85EBA6207413](https://user-images.githubusercontent.com/66970905/235928590-0efc74af-8046-425c-bcdf-199b218c0090.jpeg)

**Comment by madmachinations** [comment]
Hmmmm interesting, I also use HA in docker, no supervisor etc. And yissssssssss that is the correct Todoist API key for sure!

What is the name of your alexa shopping list in your todoist account? Is it still "Alexa Shopping List"? Or is it in Italian also :sweat_smile: ? Because that would cause a problem for sure, and would generate no error I think.

If that isn't the case, check and see if the aiohttp python module is available within your HA container.

If neither of those work, I'll add some better error reporting to the integration. So let me know what happens :blush:

**Comment by samuele2723** [comment]
Yea, still the original italian name

should i change it and repair?
![2DBD1126-0995-4C77-AF06-B197CCD975E5](https://user-images.githubusercontent.com/66970905/235933156-d1ec5afd-b2bd-428b-a063-7cc73025f083.jpeg)

**Comment by madmachinations** [comment]
Aha! That will definitely be your problem for sure!

Can you rename it to the English: "Alexa Shopping List" ?
If you can that should fix it. If it won't let you rename it then I will come up with another solution :stuck_out_tongue_closed_eyes: 

I didn't really think about other languages I'm afraid haha! :sweat_smile:

**Comment by madmachinations** [comment]
Thanks haha! I'm glad it's working for you now :partying_face: .

I would like to publish to hacs for sure! I just got bored when reading their documentation about how to do so :laughing: .

I'll add a note to the instructions about the name of that list on your todoist account, in case someone else hits the same issue :sweat_smile . It didn't even cross my mind this might be named something else in other languages haha :rofl: 

Have a good day! And thanks for helping to find the problem and for your patience :blush:
